package com.jiangyifen.ec.customer.olay.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-09-17T20:29:58.226+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "MyOlayIVRSrv", 
                  wsdlLocation = "http://olayuat.crmyymd.com/MyOlay_WS/xfire/MyOlayIVRSrv?wsdl",
                  targetNamespace = "http://IVR.myolay.www.accentiv.cn") 
public class MyOlayIVRSrv extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://IVR.myolay.www.accentiv.cn", "MyOlayIVRSrv");
    public final static QName MyOlayIVRSrvHttpPort = new QName("http://IVR.myolay.www.accentiv.cn", "MyOlayIVRSrvHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://olayuat.crmyymd.com/MyOlay_WS/xfire/MyOlayIVRSrv?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MyOlayIVRSrv.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://olayuat.crmyymd.com/MyOlay_WS/xfire/MyOlayIVRSrv?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MyOlayIVRSrv(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyOlayIVRSrv(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyOlayIVRSrv() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyOlayIVRSrv(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyOlayIVRSrv(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyOlayIVRSrv(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns MyOlayIVRSrvPortType
     */
    @WebEndpoint(name = "MyOlayIVRSrvHttpPort")
    public MyOlayIVRSrvPortType getMyOlayIVRSrvHttpPort() {
        return super.getPort(MyOlayIVRSrvHttpPort, MyOlayIVRSrvPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyOlayIVRSrvPortType
     */
    @WebEndpoint(name = "MyOlayIVRSrvHttpPort")
    public MyOlayIVRSrvPortType getMyOlayIVRSrvHttpPort(WebServiceFeature... features) {
        return super.getPort(MyOlayIVRSrvHttpPort, MyOlayIVRSrvPortType.class, features);
    }

}
